version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: |
            chmod +x gradlew
             ./gradlew clean test
      - store_artifacts:
          path: allure-report
          destination: allure-report

      - store_artifacts:
          path: test-output/ExtentReport.html
          destination: extent-report

workflows:
  version: 2
  build-test:
    jobs:
      - build