name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t gradle-tests .

      # Run tests and generate Allure report inside Docker
      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/build:/app/build \
            gradle-tests \
            ./gradlew clean test allureReport

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
          retention-days: 5

      # Upload Allure Report as artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
          retention-days: 5

  deploy-allure:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # Download Allure artifact
      - name: Download Allure artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true